#preload = /home/barbosa/Pictures/night.jpg
#wallpaper = ,/home/barbosa/Pictures/night.jpg

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/night-starts.jpg
    fit_mode = cover
}


wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/japan-fuji.jpg
    fit_mode = cover
}
